import '@radix-ui/themes/styles.css';
import './globals.css';

import { Theme, ThemePanel } from '@radix-ui/themes';

import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import NavBar from './NavBar';

const inter = Inter({
    subsets: ['latin'],
    variable: '--font-inter',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en' className={inter.variable}>
            <body>
                <Theme accentColor='iris'>
                    <NavBar />
                    <main className='p-5'>{children}</main>
                </Theme>
            </body>
        </html>
    );
}
